-- ROUND 3.
CREATE DATABASE IF NOT EXISTS hbtn_0d_usa;
-- CHANGE DB.
USE hbtn_0d_usa;
-- CREATE THE TABLE.
CREATE TABLE IF NOT EXISTS states (
    id INT AUTO_INCREMENT PRIMARY KEY NOT NULL,
    name VARCHAR(256) NOT NULL
);